"""add tournament auction settings

Revision ID: 087f01aa9211
Revises: 98150f18d45d
Create Date: 2026-08-26 19:46:57.277831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087f01aa9211'
down_revision: Union[str, Sequence[str], None] = '98150f18d45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('purse_cr', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('tournaments', sa.Column('max_overseas_players', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('max_players_per_team', sa.Integer(), nullable=False))
    op.add_column('tournaments', sa.Column('minimum_bid_increment_cr', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'minimum_bid_increment_cr')
    op.drop_column('tournaments', 'max_players_per_team')
    op.drop_column('tournaments', 'max_overseas_players')
    op.drop_column('tournaments', 'purse_cr')
    # ### end Alembic commands ###
