"""add team owner uniqueness

Revision ID: 10617288a00e
Revises: 4b37553d0285
Create Date: 2026-08-26 21:28:24.731845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10617288a00e'
down_revision: Union[str, Sequence[str], None] = '4b37553d0285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_team_tournament_owner', 'teams', ['tournament_id', 'owner_telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_team_tournament_owner', 'teams', type_='unique')
    # ### end Alembic commands ###
