"""add unique auction run player constraint

Revision ID: e56d3428db78
Revises: 9aeb77c9f6ef
Create Date: 2026-08-27 11:23:52.682668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56d3428db78'
down_revision: Union[str, Sequence[str], None] = '9aeb77c9f6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_auction_run_player', 'auction_players', ['auction_run_id', 'player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_auction_run_player', 'auction_players', type_='unique')
    # ### end Alembic commands ###
